/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JGxeD851QGg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <main className="container mx-auto py-12 px-4 md:px-6 lg:px-8">
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader>
            <CardTitle>Leave Days</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center gap-2">
            <span className="text-4xl font-bold">25</span>
            <p className="text-gray-500 dark:text-gray-400">Total leave days</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Days Taken</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center gap-2">
            <span className="text-4xl font-bold">12</span>
            <p className="text-gray-500 dark:text-gray-400">Leave days taken</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Balance</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center gap-2">
            <span className="text-4xl font-bold">13</span>
            <p className="text-gray-500 dark:text-gray-400">Remaining leave days</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Lost Hours</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center gap-2">
            <span className="text-4xl font-bold">24</span>
            <p className="text-gray-500 dark:text-gray-400">Hours lost</p>
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
